[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
todolist_addr='e16ee3557835f7ea5f5dbd7cb2fd89902afe812c59434289d0fd494650a00a61'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
