[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
todolist_addr='eb531c9b8fbf3217b9fc36334b1df42eb44ee22239ae0fec34bc115e3061cf74'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
